Update the docket_sheets_link.feature test
codeforboston/docassemble-juvenilesealing pull request #198
Opened 2021-02-13 00:09 UTC by niharikasingh

Closes #188

2021-02-13 00:21 UTC, niharikasingh reviewed
The tests for this are failing. Pourquoi?!

2021-02-13 00:22 UTC, knod requested changes
Good progress, a few changes

2021-02-13 00:22 UTC, knod commented on tests/features/docket_sheets_link.feature
>      Then I should see the phrase "Do you already have certified copies"
We're replacing phrases with IDs

2021-02-13 00:22 UTC, knod commented on tests/features/docket_sheets_link.feature
> +    Then the question id should be "do_you_have_sheets"
```
✖ Then the question id should be "do_you_have_sheets" # node_modules/docassemble-cucumber/lib/steps.js:265
       AssertionError: ~ This page's actual question id is "certified-copies-page-text-question"
```

2021-02-13 00:22 UTC, knod commented on tests/features/docket_sheets_link.feature
> +    Then the question id should be "do_you_have_sheets"
```
✖ Then the question id should be "do_you_have_sheets" # node_modules/docassemble-cucumber/lib/steps.js:265
       AssertionError: ~ This page's actual question id is "certified-copies-page-text-question"
```

2021-02-17 02:01 UTC, merged

2021-02-17 02:02 UTC, rpigneri-vol approved these changes